/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

class AppTest {
    @Test
    fun greeting_isNotBlank() {
        val classUnderTest = App()
        assertTrue("greeting should not be blank", classUnderTest.greeting.isNotBlank())
    }

    @Test
    fun greeting_matchesExpectedValue() {
        val classUnderTest = App()
        assertEquals("Hello World!", classUnderTest.greeting)
    }
}
