/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.junit.Test
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertEquals

class AppTest {
    @Test fun appHasAGreeting() {
        val classUnderTest = App()
        assertNotNull("app should have a greeting", classUnderTest.greeting)
    }

    @Test fun appSaysHello() {
        val classUnderTest = App()
        assertEquals("Hello", classUnderTest.sayHello())
    }
}
